_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# min_epochs: 1 # prevents early stopping
max_epochs: 1000000

accelerator: auto
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

gradient_clip_val: 0.5

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# Set show progress bar to False to disable it
enable_progress_bar: False
