name: tabasco

channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
  - python=3.11
  - pytorch=2.5.1
  - lightning=2.*
  - torchmetrics=0.*
  - hydra-core=1.3.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - numpy=1.*
  - pandas=2.*

  # notebook things (hopefully stable)
  - jupyter
  - jupyterlab
  - ipykernel
  - ipython

  # molecule things
  - rdkit=2024.09.4
  - conda-forge::datamol=0.12.*
  - conda-forge::openbabel=3.1.1

  - pip>=23
  - pip:
      - -e .
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
      - biotite==1.*
      - lmdb==1.*
      - tensordict==0.7.0
      - plotly==6.0.0
      - wandb==0.19.6
      - pymol-remote==1.1.0
      - posebusters==0.3.1
      - py3Dmol==2.4.2
      - ruff==0.9.9
      - posecheck==1.3.1
