_target_: tabasco.data.unconditional_datamodule.LmdbDataModule
data_dir: ${paths.root_dir}/data/processed_geom_train.pt
val_data_dir: ${paths.root_dir}/data/processed_geom_val.pt
test_data_dir: ${paths.root_dir}/data/processed_geom_test.pt
add_random_rotation: true
add_random_permutation: false
reorder_to_smiles_order: true
remove_hydrogens: true
batch_size: 256
num_workers: 0
